INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN001', "Alexandrite Dragon", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN002', "Minerva, Lightsworn Maiden", 'TODO', 'SR', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN003', "Raiden, Hand of the Lightsworn", 'TODO', 'SR', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN004', "Judgment Dragon", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN005', "Gragonith, Lightsworn Dragon", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN006', "Celestia, Lightsworn Angel", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN007', "Jain, Lightsworn Paladin", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN008', "Lyla, Lightsworn Sorceress", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN009', "Garoth, Lightsworn Warrior", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN010', "Wulf, Lightsworn Beast", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN011', "Ehren, Lightsworn Monk", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN012', "Lumina, Lightsworn Summoner", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN013', "Aurkus, Lightsworn Druid", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN014', "Shire, Lightsworn Spirit", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN015', "Ryko, Lightsworn Hunter", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN016', "Honest", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN017', "Lightray Diabolos", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN018', "Lightray Daedalus", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN019', "Vylon Prism", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN020', "Fabled Raven", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN021', "The Fabled Cerburrel", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN022', "Blackwing - Zephyros the Elite", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN023', "Necro Gardna", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN024', "Lightsworn Sanctuary", 'TODO', 'UR', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN025', "Realm of Light", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN026', "Solar Recharge", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN027', "Charge of the Light Brigade", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN028', "Monster Reincarnation", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN029', "Foolish Burial", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN030', "Glorious Illusion", 'TODO', 'C', 'Trap');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN031', "Lightsworn Barrier", 'TODO', 'C', 'Trap');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN032', "Vanquishing Light", 'TODO', 'C', 'Trap');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN033', "Beckoning Light", 'TODO', 'C', 'Trap');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN034', "Skill Successor", 'TODO', 'C', 'Trap');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN035', "Breakthrough Skill", 'TODO', 'C', 'Trap');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('SDLI', 'EN036', "Michael, the Arch-Lightsworn", 'TODO', 'UR', 'Synchro');
