INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENS01', "Slifer the Sky Dragon", 'TODO', 'UR', 'Divine');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENS02', "Obelisk the Tormentor", 'TODO', 'UR', 'Divine');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENS03', "The Winged Dragon of Ra", 'TODO', 'UR', 'Divine');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY01', "The Legendary Exodia Incarnate", 'TODO', 'UR', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY02', "Ties of the Brethren", 'TODO', 'UR', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY03', "Obliterate!!!", 'TODO', 'UR', 'Trap');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY04', "Exodia the Forbidden One", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY05', "Right Arm of the Forbidden One", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY06', "Left Arm of the Forbidden One", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY07', "Right Leg of the Forbidden One", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY08', "Left Leg of the Forbidden One", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY09', "Exodia Necross", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY10', "Dark Magician", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY11', "Dark Magician Girl", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY12', "Buster Blader", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY13', "Silent Magician LV8", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY14', "Silent Magician LV4", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY15', "The Tricky", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY16', "Big Shield Gardna", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY17', "Magician's Valkyria", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY18', "Blast Magician", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY19', "Blockman", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY20', "Marshmallon", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY21', "Sangan", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY22', "Gold Sarcophagus", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY23', "Swords of Revealing Light", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY24', "Magical Dimension", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY25', "Magicians Unite", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY26', "Tricky Spell 4", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY27', "Thousand Knives", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY28', "Dark Magic Attack", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY29', "Contract with Exodia", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY30', "Messenger of Peace", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY31', "Dark Factory of Mass Production", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY32', "Monster Reincarnation", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY33', "Secret Village of the Spellcasters", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY34', "Pot of Duality", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY35', "Mirror Force", 'TODO', 'C', 'Trap');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY36', "Magical Hats", 'TODO', 'C', 'Trap');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY37', "Magic Cylinder", 'TODO', 'C', 'Trap');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY38', "Magician's Circle", 'TODO', 'C', 'Trap');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY39', "Backup Soldier", 'TODO', 'C', 'Trap');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENY40', "Gravity Bind", 'TODO', 'C', 'Trap');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENT01', "Token", 'TODO', 'UR', 'Token');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK01', "Blue-Eyes White Dragon", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK02', "Dragon Spirit of White", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK03', "Kaibaman", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK04', "The White Stone of Legend", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK05', "The White Stone of Ancients", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK06', "Maiden with Eyes of Blue", 'TODO', 'UR', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK07', "Protector with Eyes of Blue", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK08', "Master with Eyes of Blue", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK09', "Battle Ox", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK10', "La Jinn the Mystical Genie of the Lamp", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK11', "Vorse Raider", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK12', "Alexandrite Dragon", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK13', "Blade Knight", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK14', "Ancient Lamp", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK15', "Tiger Dragon", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK16', "Kidmodo Dragon", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK17', "King of the Swamp", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK18', "Rider of the Storm Winds", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK19', "Burst Stream of Destruction", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK20', "Beacon of White", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK21', "Mausoleum of White", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK22', "Polymerization", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK23', "Enemy Controller", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK24', "Shrink", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK25', "Silent Doom", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK26', "The Melody of Awakening Dragon", 'TODO', 'UR', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK27', "Ancient Rules", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK28', "Trade-In", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK29', "Where Arf Thou?", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK30', "Pot of Dichotomy", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK31', "Fusion Substitute", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK32', "Unexpected Dai", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK33', "Negate Attack", 'TODO', 'C', 'Trap');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK34', "Final Attack Orders", 'TODO', 'C', 'Trap');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK35', "Shadow Spell", 'TODO', 'C', 'Trap');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK36', "Cloning", 'TODO', 'C', 'Trap');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK37', "Fusion Reserve", 'TODO', 'C', 'Trap');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK38', "Jar of Avarice", 'TODO', 'C', 'Trap');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK39', "Azure-Eyes Silver Dragon", 'TODO', 'C', 'Synchro');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK40', "Blue-Eyes Ultimate Dragon", 'TODO', 'UR', 'Fusion');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENK41', "First of the Dragons", 'TODO', 'C', 'Fusion');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENT02', "Token", 'TODO', 'UR', 'Token');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ01', "Red-Eyes B. Dragon", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ02', "Red-Eyes Black Flare Dragon", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ03', "Red-Eyes Archfiend of Lightning", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ04', "Red-Eyes Retro Dragon", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ05', "The Black Stone of Legend", 'TODO', 'UR', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ06', "Black Metal Dragon", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ07', "Axe Raider", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ08', "Alligator's Sword", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ09', "Baby Dragon", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ10', "Jinzo", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ11', "Goblin Attack Force", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ12', "Gearfried the Iron Knight", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ13', "Rocket Warrior", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ14', "Blue Flame Swordsman", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ15', "Time Wizard", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ16', "Phoenix Gearfried", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ17', "Gemini Summoner", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ18', "Blazewing Butterfly", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ19', "Dark Valkyria", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ20', "Command Knight", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ21', "Valkyrian Knight", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ22', "Keeper of the Shrine", 'TODO', 'C', 'Monster');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ23', "Inferno Fire Blast", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ24', "Red-Eyes Fusion", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ25', "Cards of the Red Stone", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ26', "Polymerization", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ27', "Salamandra", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ28', "Scapegoat", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ29', "Foolish Burial", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ30', "Roulette Spider", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ31', "Supervise", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ32', "Mystical Space Typhoon", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ33', "Symbols of Duty", 'TODO', 'C', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ34', "Return of the Red-Eyes", 'TODO', 'UR', 'Trap');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ35', "Red-Eyes Spirit", 'TODO', 'C', 'Trap');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ36', "Kunai with Chain", 'TODO', 'C', 'Trap');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ37', "Call of the Haunted", 'TODO', 'C', 'Trap');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ38', "Torrential Tribute", 'TODO', 'C', 'Trap');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ39', "Burst Breath", 'TODO', 'C', 'Trap');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ40', "Curse of Anubis", 'TODO', 'C', 'Trap');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ41', "Red-Eyes Flare Metal Dragon", 'TODO', 'UR', 'XYZ');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ42', "Archfiend Black Skull Dragon", 'TODO', 'C', 'Fusion');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENJ43', "Alligator's Sword Dragon", 'TODO', 'C', 'Fusion');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENT03', "Token", 'TODO', 'UR', 'Token');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENS04', "Dark Burning Attack", 'TODO', 'SE', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENS05', "Dark Burning Magic", 'TODO', 'SE', 'Spell');
INSERT INTO cards (pack_id, id, name, edition_id, rarity_id, type) VALUES ('LDK2', 'ENS06', "Eternal Soul", 'TODO', 'SE', 'Trap');
